### ISSUE TITLE
PoissonReconLib build config fails

### ISSUE THREAD

**Issue by JamesHarrison** [nine7nine/pkgz#2]
Tried to build on latest Arch and got this cropping up:

```
CMake Error at plugins/qPoissonRecon/PoissonReconLib/CMakeLists.txt:21 (add_library):
  Cannot find source file:

    Src/Hash.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

```

Disabling the Poisson reconstruction plugin in the build allows build to start, but out of the box the build fails with the above.

**Comment by nine7nine** [comment]
Hi,

it looks like upstream has switched to a new version of PoissonReconLib, you happened to pull at a bad time, as the cmaklists file no longer includes /src/hash.h ...

**\* However, there is something wrong with the new version of that lib on non-windows and the compilation fails, I'm going to have a look and i will try to fix it or provide a workaround for you (like maybe using the old version / a forked branch).

**Comment by nine7nine** [comment]
I filed a bug report, I will try to provide you with a pkgbuild / poissionreconlib that works in a bit, k?

**Comment by nine7nine** [comment]
Hi, grab this source package;

https://github.com/nine7nine/CloudCompare-Archlinux/blob/master/cloudcompare-git-2.6.2.r753.gf78df21-1.src.tar.gz

it should build, as it uses the old version of PoissonRecon... I'll update my repos later, once I have time to test everything with the new poissonreon changes and CC changes.

**Comment by nine7nine** [comment]
Hey James, 

the issue should be fixed now, when u have a chance could you try compiling CC again, using my updated pkgbuild (cloudcompare-git, assuming your using gcc)...

I've sync'd the CC to master branch to grab the PoissonReconLib changes. both my gcc and icc source packages build correctly now. thx!

please let me know, if everything works. then I can close this issue

**Comment by JamesHarrison** [comment]
Thank you very much for looking into this, @nine7nine! https://github.com/nine7nine/cloudcompare-trunk.git I can't reach though and it's required by the PKGBUILD.

**Comment by nine7nine** [comment]
Hey, I should've clarified a bit better; don't bother using the source package that I provided a link to.. (i've just deleted it anyway! lol.) ... use the normal pkgbuild for gcc; https://github.com/nine7nine/CloudCompare-Archlinux/tree/master/cloudcompare-git

I've updated it. it's sync'd to master/upstream again, using the new PoissonReconLib and builds correctly....that other source package can't find that branch because I have deleted it. 

Background;

I forked cloudcompare/trunk to apply some patches; updating libqhull/qHPR plugin and fixing the compilation for Intel C/C++ Compiler (my pkgbuild was using that branch!)... however, I am now trying to get those changes merged upstream. To clean things up for reviewing/merging upstream; I deleted the branch that you are referring to (and re-forked + applied my changes for review)... 

To fix my source packages, I then added a patch to my PKGBUILDs. ~ rather than fetching from my branch. This way, until I get my branch merged, my Arch packages will still contain those chances while staying sync'd to upstream/cloudcompare.

PKGBUILD changes; https://github.com/nine7nine/CloudCompare-Archlinux/commit/b63bf91d2fe1ccdaa50e6b0c452e0331e1ca7be5

sorry for the inconvenience, keep me posted.

EDIT: CC/upstream has merged my changes :) ... So no more patching the Archlinux build. I've updated my source packages and they both build fine here... you should be good to go.

**Comment by nine7nine** [comment]
any update on this james?

I've built CC a bunch of times, enabled a couple of features and pushed updates...

it would be nice to know if it is working for you now???

thanks

**Comment by JamesHarrison** [comment]
Sorry for the delay - looks to be working perfectly. Thank you for maintaining this package and for solving this so quickly!

**Comment by nine7nine** [comment]
sweet. i'm glad its working now.

it was really just funny timing, i think. upstream making some changes, me workin on getting changes merged... then everything just snow-balled. lol.

idk, if u were using cc before, but i've enabled the openmp support for poissionrecon. much faster processing! 😃 ...

anyway, i appreciate u letting me know about yer issues, so that i could fix my packages. thx
